apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pulse.fullname" . }}-worker
  labels:
    {{- include "pulse.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "pulse.fullname" . }}-worker
    app.kubernetes.io/component: worker
spec:
  {{- if not .Values.autoscaling.worker.enabled }}
  replicas: {{ .Values.replicaCount.worker }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pulse.fullname" . }}-worker
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "pulse.labels" . | nindent 8 }}
        app.kubernetes.io/name: {{ include "pulse.fullname" . }}-worker
        app.kubernetes.io/component: worker
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.service.worker.port }}"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: worker
          image: "{{ .Values.image.worker.repository }}:{{ .Values.image.worker.tag }}"
          imagePullPolicy: {{ .Values.image.worker.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.service.worker.port }}
          env:
            - name: REDIS_URL
              value: redis://{{ include "pulse.fullname" . }}-redis:{{ .Values.service.redis.port }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: metrics
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources.worker | nindent 12 }}