{{- if .Values.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "navidrome.fullname" . }}-music
  labels:
    {{- include "navidrome.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.music.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.music.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "navidrome.fullname" . }}-data
  labels:
    {{- include "navidrome.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.data.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
{{- end }}