apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pulse
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: lab-in-a-box
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/BubblyWolf/lab-in-a-box
    path: charts/pulse
    targetRevision: HEAD
    helm: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: pulse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true