apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-tag
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: check-latest-tag
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - kube-node-lease
                - kube-public
                - kyverno
                - argocd
                - monitoring
                - logging
                - sealed-secrets
                - trivy-system
                - local-path-storage
      validate:
        message: "Using 'latest' or untagged image tags is not recommended. Use a specific semantic version tag."
        pattern:
          spec:
            containers:
              - image: "!*:latest"
              - image: "!*:"
