apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-non-root
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: check-run-as-non-root
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - kube-node-lease
                - kube-public
                - kyverno
                - argocd
                - monitoring
                - logging
                - sealed-secrets
                - trivy-system
                - local-path-storage
      validate:
        message: "Pod must run as non-root. Set spec.securityContext.runAsNonRoot=true or container-level securityContext.runAsNonRoot=true."
        anyPattern:
          - spec:
              securityContext:
                runAsNonRoot: true
          - spec:
              containers:
                - securityContext:
                    runAsNonRoot: true
